### PR TITLE
adding grading rubric to the page

### PR DESCRIPTION
**Pull request by ajechort14**
grading rubric is not on the page

### CODE REVIEW

**Comment by aspiece** [comment]
Hello @ajechort14 

Did you see the rubric in the lesson plan?

https://tealsk12.github.io/2nd-semester-introduction-to-computer-science/units/2_unit/07_lesson/lesson.md.html

We have had feedback that having two different rubrics is confusing. Could we consider using this as more of a check list than a rubric so student know what they need to accomplish but then be scored based on the objectives of the project using the rubric in the lesson plan?

Andrew

**Comment by ajechort14** [comment]
Hi Andrew –
Yes, I saw it in the lesson plan. Some of our team got confused as it’s in the .docx file for the project but not on the project web page. Using it as a check would be great for the students – that is a great idea. Do you want we to make those changes or do you have an idea of what that would look like?

Alan

**Comment by aspiece** [comment]
Thank you @ajechort14. It would be amazing if you wouldn't mind pushing a commit. My thought was just removing the point values and giving some contextual information about how they could use the check list to ensure they include everything they need in their program.

**Review by kenneychan — COMMENTED** [review]
OK

**Pull request merged**
